GET review-comment_counter
adnaani/Adnaans-NC-GAMES-BACKEND pull request #6
Opened 2022-05-17 15:36 UTC by adnaani

2022-05-17 15:45 UTC, mallionaire requested changes
Lovely, you'll need to consider what might happen if you had a review that didn't have any comment. 
Have you written a test for that? 👀

2022-05-17 15:45 UTC, mallionaire commented on model/reviews.js
> +      console.log(rows);
Please make sure you remove console.logs

2022-05-17 15:48 UTC, adnaani commented on model/reviews.js
> +      console.log(rows);
I did considered that test after you told me but I didnt save it :( 
And I will get rid of the logs!

2022-05-18 08:11 UTC, popatre approved these changes
Looks good

2022-05-18 08:20 UTC, merged